### PR TITLE
Ensure `core` and `hdmf-common` specifications are embedded in NWBFile by default

### LINKED ISSUE #673: [Bug]: Schema are not cached in NWB file
### What happened?

I think this is new behavior, but if I create an NWB file without calling `generateCore`, the schema is not cached in the file.

Image

The `specifications` group is empty. The schema should be cached by default.

The tutorial instructions do not say to call `generateCore`.

See also https://github.com/NeurodataWithoutBorders/pynwb/issues/2046#issuecomment-2691443561

### Steps to Reproduce

```matlab
Following abbreviated steps from https://matnwb.readthedocs.io/en/latest/pages/tutorials/intro.html

1. git clone matnwb from github

addpath(genpath(pwd));
nwb = NwbFile( ...
    'session_description', 'mouse in open exploration',...
    'identifier', 'Mouse5_Day3', ...
    'session_start_time', datetime(2018, 4, 25, 2, 30, 3, 'TimeZone', 'local'));
nwbExport(nwb, 'empty_nwbfile.nwb')
```

### Error Message

```matlab

```

### Operating System

macOS

### Matlab Version

R2024b

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

### PR DESCRIPTION
**Pull request by ehennestad**
Fix #673

## Motivation
Ensure `core` and `hdmf-common` specifications are embedded by default.

## How to test the behavior?
```matlab
nwb = tests.factory.NWBFile();
nwbExport(nwb, 'test.nwb');

% Verify that core and hdmf-common were embedded in "empty" file
embeddedNamespaces = io.spec.listEmbeddedSpecNamespaces('test.nwb');
assert( isequal( sort(embeddedNamespaces), {'core', 'hdmf-common'}) )
```

## Checklist

- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/matnwb/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

File: +io/+spec/validateEmbeddedSpecifications.m
Comment (ehennestad) [inline +io/+spec/validateEmbeddedSpecifications.m:1]: Improve warning message

File: +tests/+unit/dynamicTableTest.m
Comment (ehennestad) [inline +tests/+unit/dynamicTableTest.m:1]: Fix unrelated bug in test suite

File: nwbClearGenerated.m
Comment (ehennestad) [inline nwbClearGenerated.m:1]: Fix unrelated issue. Make sure the path is actually a folder before calling rmdir

File: NwbFile.m [hunk 1]
```diff
@@ -152,12 +161,20 @@ function export(obj, filename, mode)
         function embedSpecifications(obj, output_file_id)
             jsonSpecs = schemes.exportJson();
```
Comment (ehennestad) [inline NwbFile.m:162]: This works, but ideally namespaces would get parsed and saved in the mat-file cache in the schemes.exportJson() function if the are missing. 

This would require a bit more refactoring though, and not sure if that is worth it @bendichter ?

**Review by bendichter — APPROVED** [review]
