### PR TITLE
Fix bug in `DynamicTable`'s `addColumn` method

### LINKED ISSUE #774: [Bug]: `addColumn` method of `DynamicTable` fails in certain cases
### What happened?

1. Adding two columns to a table with no columns.

``` matlab
col1 = types.hdmf_common.VectorData( ...
    'description', 'column #1', ...
    'data', [1,2,3,4] ...
);

col2 = types.hdmf_common.VectorData( ...
    'description', 'column #2', ...
    'data', [5,6,7,8]  ...
);

dynamic_table = types.hdmf_common.DynamicTable( ...
    'description', 'an example table');

dynamic_table.addColumn('col1', col1) % this works
dynamic_table.addColumn('col2', col2) % this fails
```

Error message:
```
Error using assert
New column length must match length of existing columns

Error in types.util.dynamictable.addVarargColumn (line 22)
            assert(matnwb.common.compatibility.height(new_cv.data) == tableHeight,...
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in types.util.dynamictable.addColumn (line 40)
    types.util.dynamictable.addVarargColumn(DynamicTable, varargin{:});
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in types.hdmf_common.DynamicTable/addColumn (line 115)
        types.util.dynamictable.addColumn(obj, varargin{:});
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This happens because the length to compare against is retrieved from the `id` column, but the `id` column is not initialized when adding the first column.

2. Adding a column and an index-column to a table without columns

```matlab
% Create types
col1 = types.hdmf_common.VectorData( ...
    'description', 'column #1', ...
    'data', {'1a'; '1b'; '1c'; '2a'} ...
);
col1_index = types.hdmf_common.VectorIndex( ...
    'description', 'column #1 index', ...
    'target',types.untyped.ObjectView(col1), ...
    'data', [3; 4] ...
);
table_ragged_col = types.hdmf_common.DynamicTable( ...
    'description', 'an example table');


table_ragged_col.addColumn('col1', col1, 'col1_index', col1_index)
```

Error message:
``` matlab
Unrecognized function or variable 'tableHeight'.

Error in types.util.dynamictable.addVarargColumn (line 22)
            assert(matnwb.common.compatibility.height(new_cv.data) == tableHeight,...
                                                                      ^^^^^^^^^^^
Error in types.util.dynamictable.addColumn (line 40)
    types.util.dynamictable.addVarargColumn(DynamicTable, varargin{:});
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error in types.hdmf_common.DynamicTable/addColumn (line 115)
        types.util.dynamictable.addColumn(obj, varargin{:});
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

This happens because the `tableHeight` variable is only initialized if the `id` column has data.

3. Using `addColumn` with an existing column name silently overrides that column's data and adds a duplicate name to the `DynamicTable`'s `colnames` property.

```matlab
dynamic_table = types.hdmf_common.DynamicTable( ...
    'description', 'an example table');

col1 = types.hdmf_common.VectorData( ...
    'description', 'column #1', ...
    'data', [1,2,3,4] ...
);

col2 = types.hdmf_common.VectorData( ...
    'description', 'column #2', ...
    'data', [5,6,7,8]  ...
);

dynamic_table.addColumn('col1', col1)
dynamic_table.addColumn('col1', col2)

dynamic_table
dynamic_table.vectordata.get('col1')
```

**Output**
```
dynamic_table = 

  DynamicTable with properties:

       colnames: {'col1'  'col1'}
    description: 'an example table'
             id: [1×1 types.hdmf_common.ElementIdentifiers]
     vectordata: [1×1 types.untyped.Set]


ans = 

  VectorData with properties:

    description: 'column #2'
           data: [5 6 7 8]
```

No error

### Operating System

macOS

### Matlab Version

2024b

### Code of Conduct

- [x] I agree to follow this project's [Code of Conduct](https://github.com/neurodatawithoutborders/matnwb/blob/main/.github/CODE_OF_CONDUCT.md)
- [x] Have you ensured this bug was not already [reported](https://github.com/NeurodataWithoutBorders/matnwb/issues)?

### PR DESCRIPTION
**Pull request by ehennestad**
Fix #774 

## Motivation

Fix bugs described in issue

## How to test the behavior?
See issue for examples

## Checklist

- [x] Have you ensured the PR description clearly describes the problem and solutions?
- [x] Have you checked to ensure that there aren't other open or previously closed [Pull Requests](https://github.com/neurodatawithoutborders/matnwb/pulls) for the same change?
- [x] If this PR fixes an issue, is the first line of the PR description `fix #XX` where `XX` is the issue number?

### CODE REVIEW

File: +types/+util/+dynamictable/+internal/initDynamicTableId.m [hunk 1]
```diff
@@ -0,0 +1,24 @@
...
+%   supporting older NWB versions where ElementIdentifiers were part of the
+%   core namespace.
+
+    arguments
+        dynamicTable
+        tableHeight = []
+    end
+
+    if ~isempty(tableHeight)
+        idData = int64(1:tableHeight) .' - 1;
```
Comment (ehennestad) [inline +types/+util/+dynamictable/+internal/initDynamicTableId.m]: @bendichter 
I think using 0-indexed IDs for the id column of a `DynamicTable` is something that was traditionally done for PyNWB "compatibility". Can this be reconsidered?

Comment (bendichter) [reply +types/+util/+dynamictable/+internal/initDynamicTableId.m]: why do you want to change this? I'd rather have MatNWB and PyNWB create nearly identical files by default
